%#codegen
function E_mat=EKF_Euler2DCM(a,b,c)
%angle2dcm(c,b,a)    
E_mat=...
        [1                  0                     0;...
        0                   cos(a)      sin(a);...
        0                   -sin(a)     cos(a)]...
     *        ...
        [cos(b)    0                     -sin(b);...
        0                    1                     0;                ...
        sin(b)     0                      cos(b)] ...               
     *    ...
         [cos(c)    sin(c)        0;...
         -sin(c)    cos(c)        0;...
         0                    0                       1];
end